### ISSUE TITLE
Consider Vue.js

### ISSUE THREAD

**Issue by richford** [nrdg/hbn_viewer#10]
The niivue documentation has an example for integration with Vue.js: https://github.com/niivue/niivue#vuejs-example

It might be nice to use Vue as a meta-framework because it would allow easier manipulation of UI components and the adoption of a component library. For example, issue #9 could be solved with https://primevue.org/splitter/

**Comment by neurolabusc** [comment]
@richford you can embed NiiVue into raw html, React, Vue or Angular. I would certainly stick with the framework you are most familiar with. If you are just starting out with frameworks, I would recommend React as that is what OpenNeuro, AFNI and FSL teams are using for their interface wrappers of NiiVue.  Also, the NiiVue team is using this for the electron (desktop) and capacitor (iPad) wrappers, such as [niivue-desktop](https://github.com/niivue/niivue-desktop). Choosing React will allow you to leverage existing work and feedback from those teams.

If you do prefer to stick with HTML, [here is our best effort at a pull-down menu GUI](https://niivue.github.io/niivue/features/ui.html) that works with computers, phones and tablets (touch devices do not have a `hover`).

I recognize the name `NiiVue` is misleading in this regard, reflecting an early preference for Vue. [Perhaps someday there will be new branding](https://github.com/niivue/niivue/issues/237#issuecomment-1468616602).

**Comment by arokem** [comment]
We are now using Vue, so we can close this.
