### ISSUE TITLE
Zoom

### ISSUE THREAD

**Issue by arokem** [nrdg/hbn_viewer#2]
Right now, the up and down mouse scrolling actions move the slice in the anatomical volume. I haven't found any modifier keys that change that to zoom, but zooming in and out is really useful with these kinds of visualizations, so we want to figure out how to do it here.

**Comment by IsaacCrane** [comment]
The not-great solution is apparently to press c to cycle through the clip plane options. The last of those options is to have no clip plane at all. With that setting zooming is possible and then pressing c again will return the clip plane with the new zoom still in place. Their code apparently has no other way to zoom and have the clip plane.

**Comment by neurolabusc** [comment]
Try out the `Drag` menu of the [UI live demo](https://niivue.github.io/niivue/features/ui.html) to see the built-in gestures on the 2D slices. Feel free to consider a set of default gestures for the 3D view. We do have methods to intercept the mouse gestures on the 2D slices, so this is another option. It is probably worth getting community input, as it would be great to come up with solutions that work across touch, mouse and pencil.

[NiiVue issue 599](https://github.com/niivue/niivue/issues/599) describes how you can control these features programatically.

**Comment by arokem** [comment]
This is implemented, so closing.
