### ISSUE TITLE
Bundle colors

### ISSUE THREAD

**Issue by arokem** [nrdg/hbn_viewer#5]
Use the same colors we use in all our other visualizations. For example:

https://fcp-indi.s3.amazonaws.com/data/Projects/HBN/BIDS_curated/derivatives/afq/sub-NDARAA947ZG5/ses-HBNsiteCBIC/sub-NDARAA947ZG5_ses-HBNsiteCBIC_acq-64dir_space-T1w_desc-preproc_dwi_space-RASMM_model-CSD_desc-prob-afq_viz.html

**Comment by neurolabusc** [comment]
See latest commit for [NiiVue issue 597](https://github.com/niivue/niivue/issues/597).

As an aside, I do like the ability of the viewer you linked to have streamlines thicker than one pixel. We have proposed extending NiiVue using [imposters](https://www.springerprofessional.de/en/a-simple-and-efficient-cylinder-imposter-approach-to-visualize-d/14979844) to provide nice streamlines even on low power devices. The method is currently showcased in [Surfice](https://github.com/neurolabusc/surf-ice).

**Comment by arokem** [comment]
This is in place now, so closing.
